# Generated by Django 4.1.5 on 2023-03-15 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nauczyciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klasa', models.CharField(choices=[('1', '1LOA'), ('2', '1LOB'), ('3', '2LO')], default='1', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Uczen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klasa', models.CharField(choices=[('1', '1LOA'), ('2', '1LOB'), ('3', '2LO')], default='1', max_length=10)),
                ('user1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Poprawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temat', models.CharField(max_length=50)),
                ('przedmiot', models.CharField(choices=[('Biologia', 'Biologia'), ('Chemia', 'Chemia'), ('Filozofia', 'Filozofia'), ('Fizyka', 'Fizyka'), ('Geografia', 'Geografia'), ('Historia', 'Historia'), ('Historia i teraźniejszość', 'Historia I Teraźniejszość'), ('Informatyka', 'Informatyka'), ('Język angielski', 'Język Angielski'), ('Języka polski', 'Języka Polski'), ('Język hiszpański', 'Język Hiszpański'), ('Język niemiecki', 'Język Niemiecki'), ('Matematyka', 'Matematyka'), ('Projekt społeczny', 'Projekt Społeczny'), ('Religia', 'Religia'), ('Wychowanie fizyczne', 'Wychowanie Fizyczne')], default='Chemia', max_length=60)),
                ('nauczyciel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poprawy.nauczyciel')),
                ('user1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poprawy.uczen')),
            ],
        ),
    ]
