# Generated by Django 4.1.5 on 2023-03-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poprawy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poprawa',
            name='data',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
