# Generated by Django 4.1.5 on 2023-03-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poprawy', '0002_poprawa_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poprawa',
            name='data',
            field=models.CharField(default='', max_length=50),
        ),
    ]
